#!/usr/bin/env python

import sys
import numpy as np
import rasterio

f = sys.argv[1]

with rasterio.open(f) as src:
    (l) = src.read()

counts = np.bincount(l.flatten())
print(','.join(map(str, counts.tolist())))
